export default {
    LOGIN_GUEST: 'LOGIN_GUEST',
    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    LOGOUT: 'LOGOUT',
    SET_VISIBLE_TAB_BAR: 'SET_VISIBLE_TAB_BAR',

    PROFILE_REQUEST: 'PROFILE_REQUEST',
    PROFILE_SUCCESS: 'PROFILE_SUCCESS',
    PROFILE_FAILED: 'PROFILE_FAILED',

    PENDING_LOGOUT: "PENDING_LOGOUT",

    TOAST_SHOW: 'TOATS_SHOW',
};